sudo: required
dist: trusty
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install: echo "skip bundle install"
branches:
  only:
  - master
services: docker
env:
  matrix:
  - INSTANCE=default-ubuntu-1404
before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef gem install kitchen-ec2
- chef gem install kitchen-docker
- chef gem install kitchen-transport-rsync
- "/opt/chefdk/bin/chef exec rake tests"
script:
- KITCHEN_LOCAL_YAML=.kitchen.yml
- travis_wait 30 /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
after_script:
- "/opt/chefdk/embedded/bin/kitchen destroy ${INSTANCE}"
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: qTtdE34nXqatoKyzJ7R/UibeHlicVwR7/M4qCiL2UxPsHAfe7e3Nuskkbh3BFFbTcLlzqcRIDiejCqVPAw/40vSNKifbz/VwiM5IS9rVN2BNqPuywP8EtdXCMsSwBZMFFiYmVHXj+qBhhwnGo8dcrX7Ru1FH+b9ZL4xTq3c/QH5QtrV33IH+EsXbwAWkd3+3kFKQETX+GVb8YIgHQWdEFGKqTBu/u3E45U5cNIzr5LhK2KgL7v/4PYH/p8jyD+ueqMfP4IqsjXTWhLWHcd3fkyqfVYQ9SUnRwFe/w2GekBnwTQr/7C33etMWVHgbmFtrREdwRfWVDg2OLtFNmpnxqSW9fhc6bMwiSm6JBhFLAPBfwr1R9OVomzUGBYtBywf8xqtTGelx2kCLzx+AMnK9P83SkUoeokwtwWfQbGN7Ft817vlYY/wYi9opckq0HN+N4lAPex8Ko1rk2hEqKAVvuNK481y+QoPFnOA9NckRQqTh0eErrU+5Ydj8+7XxFeUAHe/V6OCKlmovDloZ0pQtoEwEIj7+n3Nt3tmJxTLNV0nQOISC7IHjUxe3gPa4PsO5s2htrWy2L9bME7uO6FCMQTRslyWCxqUMRmMXTf7scUSTUiYDmcdBjZ9ON2nCwxUfHS6MKuwZ7k9toARZKb8/TMaQeVjPvorVwbT1QiPIgDE=
